update libraries to version from 2.35

diff --git a/install b/install
--- a/install
+++ b/install
@@ -16,7 +16,7 @@
 # WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
 # MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 #
-# $Header: /nfs/jade/vint/CVSROOT/ns-2/allinone/install,v 1.28 2005/02/01 18:04:45 haldar Exp $
+# $Header: /cvsroot/nsnam/ns-2/allinone/install,v 1.31 2007/03/10 23:40:05 tom_henderson Exp $
 
 die() {
 	echo "$@"  1>&2
@@ -64,7 +64,7 @@ test_packages() {
 }
 
 cygwin_tests() {
-        echo -n "Checking Cygwin version is >= 1.3.12... "
+        echo -n "Checking Cygwin version is >= 1.7.1... "
         cmaj=` uname -r | sed -e 's/^\([0-9]*\)\.\([0-9]*\).\([0-9]*\).*/\1/'`;
         echo $cmaj | grep -v [0-9] >/dev/null 2>&1
         if [ "$?" -eq "0" ]; then
@@ -81,13 +81,13 @@ cygwin_tests() {
                 cpat=0;
         fi;
         echo -n "$cmaj.$cmin.$cpat ";
-        if ([ "$cmaj" -gt "1" ]) || ([ "$cmaj" -eq "1" ] && [ $cmin -gt "3" ]) || ([ "$cmaj" -eq 1 ] && [ $cmin -eq "3" ] && [ "$cpat" -ge "12" ]); then
+        if ([ "$cmaj" -gt "1" ]) || ([ "$cmaj" -eq "1" ] && [ $cmin -gt "7" ]) || ([ "$cmaj" -eq 1 ] && [ $cmin -eq "7" ] && [ "$cpat" -ge "1" ]); then
                 echo "(should be ok)";
         else
                 echo "(NO!)";
                 echo "";
                 echo "ns-allinone-${NSVER} has not been tested under versions of Cygwin older than";
-                echo "1.3.12. Your version ($cmaj.$cmin.$cpat) appears to be older than that. Success of";
+                echo "1.7.1. Your version ($cmaj.$cmin.$cpat) appears to be older than that. Success of";
                 echo "the install process is therefore NOT GUARANTEED.";
                 echo "";
                 cygversion="failed";
@@ -175,48 +175,37 @@ cygwin_tests() {
         fi;     
 
         echo -n "Checking for X... ";
-        cygcheck -c xorg-x11-base | grep xorg-x11-base >/dev/null 2>&1;
-        if [ "$?" -eq "0" ]; then
-                echo "X.org";
-                test_packages ${packages_xorg}
-                
-        else
-                cygcheck -c XFree86-base | grep XFree86-base >/dev/null 2>&1;
-                if [ "$?" -eq "0" ]; then
-                        echo "XFree86";
-                        test_packages ${packages_xfree}                                              
-                else 
-                        echo "None found!";
-                        
-                        echo "";
-                        echo "Neither Package xorg-x11-base nor XFree86-base is present on your system.";
-                        echo "";
-                        echo "Please install one of it using Cygwin's setup.exe";
-                        echo "before trying to install the ns-2 distribution.";
-                        test_proceed;
-                        
-                 fi;
-        fi;
+        test_packages ${packages_xorg}
     }
 
 
 # Package VERSIONs. Change these when releasing new packages
-TCLVER=8.4.11
-TKVER=8.4.11
-OTCLVER=1.11
-TCLCLVER=1.17
-NSVER=2.29
-NAMVER=1.11
-XGRAPHVER=12.1
+TCLVER=8.5.10
+TKVER=8.5.10
+OTCLVER=1.14
+TCLCLVER=1.20
+NSVER=2.35
+NAMVER=1.15
+XGRAPHVER=12.2
 ZLIBVER=1.2.3
+DEI80211MRVER=1.1.4
 
 # Get current path
 CUR_PATH=`pwd`
 
+echo "============================================================"
+echo "* Testing for Darwin (OS X) environment"
+echo "============================================================"
+if  [ `uname` = "Darwin" ]; then
+    echo "Darwin detected";
+    DYLD_LIBRARY_PATH=$CUR_PATH/tcl$TCLVER/unix:$CUR_PATH/tk$TKVER/unix:$DYLD_LIBRARY_PATH
+    export DYLD_LIBRARY_PATH
+    test_darwin=true
+fi
+
 # A Cygwin install requires these packages:
-packages_base="gcc gcc-g++ gawk tar gzip make patch perl w32api"
-packages_xfree="XFree86-bin XFree86-prog XFree86-lib XFree86-etc"
-packages_xorg="xorg-x11-bin xorg-x11-bin-dlls xorg-x11-devel xorg-x11-libs-data xorg-x11-etc"
+packages_base="gcc4 gcc4-g++ gawk tar gzip make patch perl w32api"
+packages_xorg="xorg-server xinit libX11-devel libXmu-devel"
 
 # Check if we are using Cygwin, and if so, if it is a good install
 # Most Cygwin fixes in the tree and this part of the install script were 
@@ -259,7 +248,18 @@ else
         echo "Cygwin not detected, proceeding with regular install.";
 fi;
 
-
+echo "============================================================"
+echo "* Testing for FreeBSD environment"
+echo "============================================================"
+# See if we need to use gmake.
+if [ "`uname -s`" = "FreeBSD" ]; then
+ echo "FreeBSD detected; using gmake instead of make"
+ if (type gmake &>/dev/null); then
+   alias make="gmake"
+ fi
+else
+ echo "FreeBSD not detected"
+fi
 
 # Compile and install xgraph
 
@@ -272,7 +272,7 @@ cd ./xgraph-$XGRAPHVER
 if  [ "${test_cygwin}" = "true" ]; then
        touch stamp-h;
 fi;
-if make
+if make 
 then
 	echo "xgraph has been installed successfully. "
 else 
@@ -393,7 +393,7 @@ fi
 
 cd ../
 
-# Build Tcl8.4.5
+# Build Tcl8.4.18
 
 echo "============================================================"
 echo "* Build tcl$TCLVER"
@@ -406,13 +406,15 @@ fi
 
 blame='Tcl is not part of the ns project.  Please see www.Scriptics.com
 to see if they have a fix for your platform.'
-./configure --enable-gcc --disable-shared --prefix=$CUR_PATH || die "tcl8.3.2 configuration failed! Exiting ..."
+autoconf
+./configure --enable-gcc --disable-shared --prefix=$CUR_PATH || die "tcl$TCLVER configuration failed! Exiting ..."
 if make 
 then 
 	echo "tcl$TCLVER make succeeded."
 	make install || die "tcl$TCLVER installation failed."
+	make install-private-headers || die "tcl$TCLVER installation failed."
 	echo "tcl$TCLVER installation succeeded."
-	cp ../generic/*.h ../../include
+	#cp ../generic/*.h ../../include
 else
 	echo "tcl$TCLVER make failed! Exiting ..."
 	echo "For problems with Tcl/Tk see http://www.scriptics.com"
@@ -434,11 +436,13 @@ fi
 
 blame='Tk is not part of the ns project.  Please see www.Scriptics.com
 to see if they have a fix for your platform.'
-./configure --enable-gcc --disable-shared --prefix=$CUR_PATH || die "tk8.3.2 configuration failed! Exiting ..."
+autoconf
+./configure --enable-gcc --disable-shared --disable-xft --disable-xss --prefix=$CUR_PATH || die "tk$TKVER configuration failed! Exiting ..."
 if make 
 then
 	echo "tk$TKVER build succeeded."
 	make install || die "tk$TKVER installation failed."
+	make install-private-headers || die "tcl$TCLVER installation failed."
 	echo "tk$TKVER installation succeeded."
 else
 	echo "tk$TKVER make failed! Exiting ..."
@@ -452,10 +456,14 @@ cd ../../
 # Since our configures search for tclsh in $PATH, the following 
 # is needed. This is necessary for otcl/tclcl/ns/nam
 #
-PATH=$CUR_PATH/tcl$TCLVER/unix:$CUR_PATH/tk$TKVER/unix:$PATH
-export PATH
-LD_LIBRARY_PATH=$CUR_PATH/tcl$TCLVER/unix:$CUR_PATH/tk$TKVER/unix:$LD_LIBRARY_PATH
-export LD_LIBRARY_PATH
+#PATH=$CUR_PATH/tcl$TCLVER/unix:$CUR_PATH/tk$TKVER/unix:$PATH
+#LD_LIBRARY_PATH=$CUR_PATH/tcl$TCLVER/unix:$CUR_PATH/tk$TKVER/unix:$LD_LIBRARY_PATH
+
+# However, the above library path setting has been found to be still 
+# fragile for systems that have multiple versions of Tcl/Tk installed
+# in various places, so in the below, we will force the allinone build
+# to use the tcl/tk version installed with allinone by passing the
+# --with-tcl-ver and --with-tk-ver options
 
 # Build otcl
 
@@ -468,18 +476,26 @@ cd ./otcl-$OTCLVER
 blame='Please check http://www.isi.edu/nsnam/ns/ns-problems.html
 for common problems and bug fixes.'
 if  [ "${test_cygwin}" = "true" ]; then
-        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include || die "otcl-$OTCLVER configuration failed! Exiting ...";
+        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER --disable-shlib || die "otcl-$OTCLVER configuration failed! Exiting ...";
+	if make 
+	then
+		echo "otcl-$OTCLVER has been installed successfully."
+	else
+		echo "otcl-$OTCLVER make failed! Exiting ..."
+		echo "See http://www.isi.edu/nsnam/ns/ns-problems.html for problems"
+		exit
+	fi
 else
-        ./configure || die "otcl-$OTCLVER configuration failed! Exiting ...";
-fi
+        ./configure --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "otcl-$OTCLVER configuration failed! Exiting ...";
 
-if make 
-then
-	echo "otcl-$OTCLVER has been installed successfully."
-else
-	echo "otcl-$OTCLVER make failed! Exiting ..."
-	echo "See http://www.isi.edu/nsnam/ns/ns-problems.html for problems"
-	exit
+	if make 
+	then
+		echo "otcl-$OTCLVER has been installed successfully."
+	else
+		echo "otcl-$OTCLVER make failed! Exiting ..."
+		echo "See http://www.isi.edu/nsnam/ns/ns-problems.html for problems"
+		exit
+	fi
 fi
 
 cd ..
@@ -493,9 +509,9 @@ echo "============================================================"
 cd ./tclcl-$TCLCLVER
 
 if  [ "${test_cygwin}" = "true" ]; then
-        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include || die "tclcl-$TCLCLVER configuration failed! Exiting ...";
+        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "tclcl-$TCLCLVER configuration failed! Exiting ...";
 else
-        ./configure || die "tclcl-$TCLCLVER configuration failed! Exiting ..."
+        ./configure --with-otcl=../otcl-$OTCLVER --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "tclcl-$TCLCLVER configuration failed! Exiting ..."
 fi
 
 if make
@@ -522,9 +538,9 @@ if [ -f Makefile ] ; then
 fi
 
 if  [ "${test_cygwin}" = "true" ]; then
-        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include || die "Ns configuration failed! Exiting ...";
+        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "Ns configuration failed! Exiting ...";
 else
-        ./configure || die "Ns configuration failed! Exiting ...";
+        ./configure --with-otcl=../otcl-$OTCLVER --with-tclcl=../tclcl-$TCLCLVER --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "Ns configuration failed! Exiting ...";
 fi
 
 if make
@@ -544,23 +560,55 @@ echo "============================================================"
 echo "* Build nam-$NAMVER"
 echo "============================================================"
 
+ln -s otcl-$OTCLVER otcl
+ln -s tclcl-$TCLCLVER tclcl
+
 cd ./nam-$NAMVER
 
+# XXX temporary OS X hack
+if  [ "${test_darwin}" = "true" ]; then
+ln -s /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation libcorefoundation.dylib
+fi
+
 if  [ "${test_cygwin}" = "true" ]; then
-        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tclcl=$CUR_PATH/tclcl-$TCLCLVER  || die "Nam configuration failed! Exiting ...";
+        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tclcl=$CUR_PATH/tclcl-$TCLCLVER  --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "Nam configuration failed! Exiting ...";
 else
-        ./configure --with-tclcl=$CUR_PATH/tclcl-$TCLCLVER  || die "Nam configuration failed! Exiting ...";
+        ./configure --with-otcl=../otcl-$OTCLVER --with-tclcl=../tclcl-$TCLCLVER --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "Nam configuration failed! Exiting ...";
 fi
 
 if make
 then 
     echo "Nam has been installed successfully."
+elif  [ "${test_darwin}" = "true" ]; then
+    # XXX workaround for OS X nam Tcl/Tk problems
+    echo "Nam make failed! Trying to relink..."
+    echo "g++ -o nam tkcompat.o tkUnixInit.o xwd.o netview.o netmodel.o edge.o packet.o node.o main.o trace.o queue.o drop.o animation.o agent.o feature.o route.o transform.o paint.o state.o monitor.o anetmodel.o rng.o view.o graphview.o netgraph.o tracehook.o lan.o psview.o group.o editview.o tag.o address.o animator.o wnetmodel.o nam_stream.o enetmodel.o testview.o parser.o trafficsource.o lossmodel.o queuehandle.o gen/version.o gen/nam_tcl.o  ../tcl8.5.10/unix/libtcl8.5.a ../tk8.5.10/unix/libtk8.5.a ../tcl8.5.10/unix/libtclstub8.5.a -L../tclcl-1.20 -ltclcl -L../otcl -lotcl -L/usr/lib -lz -L/usr/X11R6/lib -lXext -lX11 -lm -L. -lcorefoundation"
+    g++ -o nam tkcompat.o tkUnixInit.o xwd.o netview.o netmodel.o edge.o packet.o node.o main.o trace.o queue.o drop.o animation.o agent.o feature.o route.o transform.o paint.o state.o monitor.o anetmodel.o rng.o view.o graphview.o netgraph.o tracehook.o lan.o psview.o group.o editview.o tag.o address.o animator.o wnetmodel.o nam_stream.o enetmodel.o testview.o parser.o trafficsource.o lossmodel.o queuehandle.o gen/version.o gen/nam_tcl.o  ../tcl8.5.10/unix/libtcl8.5.a ../tk8.5.10/unix/libtk8.5.a ../tcl8.5.10/unix/libtclstub8.5.a -L../tclcl-1.20 -ltclcl -L../otcl -lotcl -L/usr/lib -lz -L/usr/X11R6/lib -lXext -lX11 -lm -L. -lcorefoundation
+    if [ -e nam ]; then
+        echo "Nam relinking succeeded; nam has been installed successfully."
+    else
+        echo "Nam make failed! You may want to tweak the above linker path if libraries are not being picked up successfuly.  Continue ..."
+        echo "See http://www.isi.edu/nsnam/ns-problems.html for problems"
+    fi
 else
     echo "Nam make failed! Continue ..."
     echo "See http://www.isi.edu/nsnam/ns-problems.html for problems"
 fi
 
 cd ../
+
+
+
+# Building dei80211mr
+
+cd ./dei80211mr-${DEI80211MRVER}
+
+./configure --with-ns-allinone=${CUR_PATH} --prefix=${CUR_PATH} \
+    && make \
+    && make install
+
+cd ..
+
 
 # Install nam, ns, xgraph into bin
 
@@ -598,6 +646,7 @@ else
     echo "Please compile your gt-itm & sgb2ns separately."
 fi
 
+echo ""
 echo "Ns-allinone package has been installed successfully."
 echo "Here are the installation places:"
 echo "tcl$TCLVER:	$CUR_PATH/{bin,include,lib}"
@@ -640,8 +689,6 @@ echo ""
 echo "(2) You MUST put $CUR_PATH/tcl$TCLVER/library into your TCL_LIBRARY environmental"
 echo "    variable. Otherwise ns/nam will complain during startup."
 echo ""
-echo "(3) [OPTIONAL] To save disk space, you can now delete directories tcl$TCLVER "
-echo "    and tk$TKVER. They are now installed under $CUR_PATH/{bin,include,lib}"
 echo ""
 echo "After these steps, you can now run the ns validation suite with"
 echo "cd ns-$NSVER; ./validate"
