add tcl-debug in install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -184,6 +184,7 @@ TCLVER=8.5.10
 TKVER=8.5.10
 OTCLVER=1.14
 TCLCLVER=1.20
+TCLDEBUGVER=2.0
 NSVER=2.35
 NAMVER=1.15
 XGRAPHVER=12.2
@@ -525,6 +526,32 @@ fi
 
 cd ../
 
+echo "============================================================"
+echo "* Build tcl-debug-$TCLDEBUGVER"
+echo "============================================================"
+
+cd ./tcl-debug-$TCLDEBUGVER
+if [ -f Makefile ] ; then 
+    make distclean
+fi
+
+# TODO test_cygwin
+# ./configure --with-otcl=../otcl-$OTCLVER --with-tclcl=../tclcl-$TCLCLVER --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "Ns configuration failed! Exiting ...";
+./configure --with-tcl="${CUR_PATH}/lib" --with-tclinclude="$CUR_PATH/tcl$TCLVER/generic" --prefix=${CUR_PATH} --enable-gcc || die "Ns configuration failed! Exiting ..."
+
+if make
+then
+    echo "tcl-debug-$TCLDEBUGVER make succeeded."
+    make install || die "tcl$TCLVER installation failed."
+    echo "tcl-debug-$TCLDEBUGVER installation succeeded."
+else
+    echo "tcl-debug-$TCLDEBUGVER make failed! Exiting ..."
+    exit
+fi
+
+cd ..
+
+
 # John's hack
 test -f ./otcl-$OTCLVER/libotcl.a && rm ./otcl-$OTCLVER/libotcl.so
 
@@ -540,7 +567,7 @@ fi
 if  [ "${test_cygwin}" = "true" ]; then
         ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "Ns configuration failed! Exiting ...";
 else
-        ./configure --with-otcl=../otcl-$OTCLVER --with-tclcl=../tclcl-$TCLCLVER --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "Ns configuration failed! Exiting ...";
+        ./configure --with-otcl=../otcl-$OTCLVER --with-tclcl=../tclcl-$TCLCLVER --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER  --with-tcldebug || die "Ns configuration failed! Exiting ...";
 fi
 
 if make
